GET http://localhost:3001/workers

POST http://localhost:3001/workers
Content-Type: application/json

{
   "trabajador": "1",
   "dispositivo": 742930,
   "hora": "08:39:23",
   "fecha": "2022-11-09"
}